### PR TITLE
Resolution for issues 3, 6, 7

### PR DESCRIPTION
**Pull request by wifiprintguy**
Since the changes for all 3 of these issues basically affect the same lines in the 3 "tests/*-tests.sh" files, the resolutions for all 3 of these issues are bundled into 1 pull request.

### CODE REVIEW

**Comment by wifiprintguy** [comment]
By the way, I intend to withdraw my first pull request, since a) the fork is now gone; and b) the changes in that first pull request bundled too many changes together, so I'm creating smaller pull requests, of which this is the first smaller one.

**Comment by michaelrsweet** [comment]
Looks good; my only minor nit is to purge occurrences of "OS X", replacing them with "macOS". :)

**Comment by wifiprintguy** [comment]
So, discuss at next IPP WG meeting to approve pull request?

**Comment by michaelrsweet** [comment]
Sure, sounds good.

**Pull request merged**
